#! /bin/bash

#*******************************************************************************
# Copyright (c) 2025 Zipline International, Inc.  All rights reserved.
#
# bargo provides some conveniences for building and running bazel targets.
#
# To use bargo, source this file in your .bashrc.
#
# The main contribution is supporting package aliases: Cargo packages within
# the bazel workspace can be referenced by package name rather than by fully-
# qualified bazel paths.
#
# For example:
#   `bargo run vio_visualizer:bin <some_args>`
# will resolve to:
#   `bazel run //FlightCode/perception/vision/vio_visualizer:bin -- <some_args>`
#
# bargo provides a convenience command, `bargo cd` (alias `bcd`), which allows the
# user to cd into a package directory by name (e.g. `bcd navigation/params`).
#
# bargo also provides aliases for several common flags. For example,
#  `bargo build --no-clippy vio`
# will resolve to:
#  `bazel build --output_groups=-clippy_checks //FlightCode/perception/vision/vio`
#
# A "--print" flag added to a command before the "--" delimiter will make bargo
# evaluate the command and write to terminal without executing it.
#
# bargo provides bash autocompletion for all targets and flags.
#================================================================================

# We'll want some nice autocomplete features from bazel.
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. $SCRIPT_DIR/bazel-complete.bash

if [ -z "${REPO_PATH}" ]; then
    echo "Error: REPO_PATH variable is not defined. bargo will not work."
fi

# Path to cache file. We generate a package:path map file once and continue to use it for lookups.
BARGO_CACHE_PATH=${BARGO_CACHE_PATH:-"$HOME/.cache/bargo_cache"}

# Generate a file that maps package names to their full paths.
function _bargo_cache {
    local CARGO_DIRS
    # Find all directories containing a Cargo.toml, excluding the root.
    CARGO_DIRS=$(find "$REPO_PATH" -name Cargo.toml -not -path "$REPO_PATH/Cargo.toml" | xargs dirname)
    # Now filter down to just the directories with a BUILD.bazel file and make a key/value pair for each
    # e.g: my_package /home/user/repo/subdir/my_package
    find $CARGO_DIRS -maxdepth 1 -name BUILD.bazel | xargs dirname | sed 's:\(.*\)/\(.*\):\2 \1/\2:g' > "$BARGO_CACHE_PATH"
}

# If no cache exists, create one.
function _maybe_bargo_cache {
    if [[ ! -f "$BARGO_CACHE_PATH" ]]; then
        _bargo_cache
    fi
}

# Given a package name, get the full path to the package root.
function _bargo_get_path {
    # Allow for queries like "package/arbitrary/path/in/package" where $PACKAGE would be "package"
    # and $SUB_DIR would be "arbitrary/path/in/package"
    IFS='/' read -r PACKAGE SUB_DIR <<< "$1"

    # If no arg, assume the user wanted the repo root.
    if [[ -z "$PACKAGE" ]]; then
        echo "$REPO_PATH"
        return
    fi

    # Read the cache and return the entry for the specified package.
    sed -n "s:^$PACKAGE \(.*\):\1/$SUB_DIR:p" "$BARGO_CACHE_PATH"
}

# List all subdirectories within a package.
function _bargo_list_subdirectories {
    local PACKAGE SUB_DIR PACKAGE_DIR

    # Split query into package an subdirectory.
    IFS='/' read -r PACKAGE SUB_DIR <<< "$1"

    # Get the package directory
    PACKAGE_DIR=$(_bargo_get_path "$PACKAGE")
    find "$PACKAGE_DIR" -type d -printf "$PACKAGE/%P\n"
}

# List all supported packages.
function _bargo_list_packages {
    _maybe_bargo_cache
    # Get all package names.
    awk '{print $1}' "$BARGO_CACHE_PATH"
}

# List all supported packages appended with a /.
function _bargo_list_packages_with_slash {
    _maybe_bargo_cache
    # Get all package names and append a /
    awk '{out=$1; out=out"/"; print out}' "$BARGO_CACHE_PATH"
}

# List all bazel targets available under a specified package.
function _bargo_list_targets_under_package {
    # Grab the build file for the package and try to parse as many target names as possible.
    local BUILD_FILE
    BUILD_FILE=$(_bargo_get_path "$1")/BUILD.bazel

    if [[ -f "$BUILD_FILE" ]]; then
        # We'll just straight-up search for 'name = "..."'
        # We have bazel-complete handy, but it doesn't do anything much more interesting than this.
        sed -n "s: *name = \"\(.*\)\",:\1:p" "$BUILD_FILE"
    fi
}

# cd into the specified package's directory.
function bargo_cd {
    _maybe_bargo_cache
    PACKAGE_PATH=$(_bargo_get_path "$1")

    if [[ -z "$PACKAGE_PATH" ]]; then
         echo "Package $PACKAGE not found. Try running \"bargo cache\" to rebuild the cache."
    else
         cd "$PACKAGE_PATH" || exit
    fi
}

# Bash completion for bargo_cd.
function _bargo_cd_complete {
    _maybe_bargo_cache
    local cur

    _init_completion || return

    if [[ $cur == */* ]]; then
        COMPREPLY=($(compgen -W "$(_bargo_list_subdirectories "$cur")" -- "$cur"))
    else
        COMPREPLY=($(compgen -W "$(_bargo_list_packages_with_slash)" -- "$cur"))
    fi
}

complete -o nospace -F _bargo_cd_complete bargo_cd

# Given an input of the form package:target, resolve a full bazel path tothe target.
function _bargo_resolve_target {
    TARGET=$1

    # Handle the easy cases.
    if [[ "$TARGET" == @* || "$TARGET" == //* ]]; then
        # The user fully specified the target. There's nothing to do.
        echo "$TARGET"
    else
        # If specified as package:target, split into parts.
        IFS=':' read -r PACKAGE TARGET <<< "$TARGET"

        # Strip out path relative to root.
        FULL_PACKAGE_PATH=$(_bargo_get_path "$PACKAGE")
        if [[ -z "$FULL_PACKAGE_PATH" ]]; then
            # Probably invalid. Give up.
            echo ""
        else
            RELATIVE_PACKAGE_PATH=$(realpath --relative-to "$REPO_PATH" "$FULL_PACKAGE_PATH")

            # Now qualify the target.
            if [[ -n "$TARGET" ]]; then
                if [[ $TARGET == "..." ]]; then
                    TARGET="/..."
                else
                    TARGET=":$TARGET"
                fi
            fi

            # We have all the parts we need.
            echo "//$RELATIVE_PACKAGE_PATH$TARGET"
        fi
    fi
}

# Supported bargo-specific commands.
_supported_bargo_commands=(cd cache outputs)

# Check that the specified command is supported.
function _bargo_validate_command {
    local supported_bazel_commands
    read -a supported_bazel_commands <<< "$BAZEL_COMMAND_LIST"
    [[ " ${_supported_bargo_commands[*]} " =~ " $1 " ]] || [[ " ${supported_bazel_commands[*]} " =~ " $1 " ]]
}

# Supported bargo-specific flags.
_supported_bargo_flags=(--no-clippy --perf --aarch64 --print --fast --debug --opt)

# Active bargo flags for the current invocation.
_active_bargo_flags=()

# Given a custom flag, resolve to bazel flag.
function _bargo_parse_flag {
    case $1 in
        --no-clippy)
            _active_bargo_flags+=("--output_groups=-clippy_checks")
            ;;
        --aarch64)
            _active_bargo_flags+=("--config=compute_ziplinux_jetson_gcc")
            ;;
        --perf)
            _active_bargo_flags+=("--run_under=perf record -F 1500 --call-graph dwarf --output $HOME/data/perf.data")
            ;;
        --fast)
            _active_bargo_flags+=("--compilation_mode=fastbuild")
            ;;
	--debug)
            _active_bargo_flags+=("--compilation_mode=dbg")
            ;;
	--opt)
            _active_bargo_flags+=("--compilation_mode=opt")
            ;;
    esac
}

# Check if the specified command expects a bazel target.
function _bargo_command_expects_target {
    case $1 in
        build|run|test|cquery)
            return 0
            ;;
        *) return 1
            ;;
    esac
}

# Entrypoint for all this nonsense.
function bargo {
    local ARG COMMAND BAZEL_TARGET PRINT_ONLY ARG_DELIMITER

    # The first argument is always a command we'll forward to bazel.
    COMMAND=$1

    # Reset active flags.
    _active_bargo_flags=()

    if ! _bargo_validate_command $COMMAND; then
        echo "Invalid command: $COMMAND. Unable to proceed."
        return 1
    fi

    # I lied; there are exceptions.
    if [[ $COMMAND = "cd" ]]; then
        bargo_cd "$2"
        return
    elif [[ $COMMAND = "cache" ]]; then
        _bargo_cache
        return
    elif [[ $COMMAND = "outputs" ]]; then
        # "outputs" is a command shortcut that we can conveniently intercept and correct here.
        COMMAND="cquery"
        _active_bargo_flags+=("--output=files")
    fi

    while shift; do
        ARG=$1

        # If parsing flags.
        if [[ "$ARG" == -* ]]; then
            if [[ "$ARG" == "--" ]]; then
                # Anything after -- is meant for the target itself. Break and allow $@ to fall through.
                shift
                break
            elif [[ "$ARG" == "--print" ]]; then
                # Special handling. The user wants to see the resolved command without actually
                # running it.
                PRINT_ONLY=true
            elif [[ " ${_supported_bargo_flags[*]} " =~ " $ARG " ]]; then
                # This is a bargo-specific flag.
                _bargo_parse_flag "$ARG"
            elif [[ "$ARG" == --*=* ]]; then
                # This is a flag of type --flag=value, which we can forward directly as a single token.
                _active_bargo_flags+=("$ARG")
            else
                # Two possible options. We either have a standalone bazel flag, or we have a key/value
                # pair where the user didn't use an = sign. Determine which one this is by looking at
                # supported bazel options. Of course, bazel also allows shorthand versions of these flags,
                # which we unfortunately can't query, but we can brute-force the ones we use often.

                # Push the arg no matter what
                _active_bargo_flags+=("$ARG")

                # Now see if we need to pop the next arg and push it.
                BAZEL_OPTIONS=$(_bazel__options_for $COMMAND)
                if _bazel__options_for "$COMMAND" | grep -q "${ARG:2}=" || [[ "$ARG" == "-c" ]]; then
                    # Yup, pop it.
                    _active_bargo_flags+=("$2")
                    shift
                fi
            fi
        elif [[ -z "$BAZEL_TARGET" ]]; then
            # We're not parsing a flag and we haven't hit --, so this might be our target.
            if _bargo_command_expects_target $COMMAND; then
                BAZEL_TARGET=$(_bargo_resolve_target "$ARG")
                if [[ -z "$BAZEL_TARGET" ]]; then
                    echo "Unable to find \"$ARG\". Try running \"bargo cache\" to build the cache."
                    return 1
                fi

                # If the next arg is not a delimiter, force one here.
                if [[ ! $2 == "--" ]]; then
                    ARG_DELIMITER="--"
                fi

                shift
                break
            else
                # We have a command, flags, and maybe a target. Everything else must be meant as arguments
                # to the target itself.
                break
            fi
        else
            # We have a command, flags, and a target. Everything else must be meant as arguments
            # to the target itself.
            break
        fi
    done

    if [[ "$PRINT_ONLY" == true ]]; then
        echo bazel "$COMMAND" "${_active_bargo_flags[@]}" "$BAZEL_TARGET" "$ARG_DELIMITER" "$@"
    else
        # Execute. Surely, things won't work outside of the repo path.
        pushd $REPO_PATH > /dev/null
        bazel "$COMMAND" "${_active_bargo_flags[@]}" "$BAZEL_TARGET" "$ARG_DELIMITER" "$@"
        popd > /dev/null
    fi
}

# Bash completion for bargo.
function _bargo_complete {
    local COMMAND DISPLACEMENT

    _maybe_bargo_cache

    # Don't tokenize on :
    _get_comp_words_by_ref -n : cur

    if _bazel__is_after_doubledash; then
        # We have no power here.
        COMPREPLY=()
    elif [[ $cur == -* ]]; then
        # Grab a command if we can.
        COMMAND=${COMP_WORDS[1]}
        # Parsing a flag. Use bazel build flags and supported bargo flags.
        COMPREPLY=($(compgen -W "$(_bazel__options_for $COMMAND) ${_supported_bargo_flags[*]}" -- "$cur"))
    elif [[ $cur == //* ]] || [[ $cur == @* ]]; then
        # Probably best to let bazel handle this one.
        DISPLACEMENT="$(_bazel__get_displacement ${REPO_PATH})"
        _bazel__to_compreply "$(_bazel__complete_pattern "$REPO_PATH" "$DISPLACEMENT" "$cur" "label")"
    elif [[ $cur == *:* ]]; then
        # Some special handling if this looks like a package:target pattern.
        IFS=':' read -r PACKAGE TARGET <<< "$cur"

        COMPREPLY=($(compgen -W "$(_bargo_list_targets_under_package "$PACKAGE")" -- "$TARGET"))
    else
        # Two likely options: either the user wants the command completed, or they want the target completed.
        if [[ $COMP_CWORD == 1 ]]; then
            # First word. Treat as a command
            COMPREPLY=($(compgen -W "$BAZEL_COMMAND_LIST  ${_supported_bargo_commands[*]}" -- "$cur"))
        else
            if [[ ${COMP_WORDS[1]} == "cd" ]]; then
                # User is executing "bargo cd". We have some fancy completion for bargo_cd. Use it here.
                _bargo_cd_complete
            else
                # If we're here, the user is probably trying to complete a target.
                COMPREPLY=($(compgen -W "$(_bargo_list_packages)" -- "$cur"))
            fi
        fi
    fi
}

complete -o nospace -o default -F _bargo_complete bargo

# Aliases
alias bcd="bargo cd $@"
complete -o nospace -F _bargo_cd_complete bcd
