#!/bin/bash
set -e

# symlink all log files to the current directory.
find -name *.zst -exec ln -s {} . \;

# symlink all video files to the current directory.
find -name *.h265 -exec ln -s {} . \;

# Flatten logs and remove symlinks.
zml -z *.zml.0.zst flatten --fix -o log.zml && rm *.zml.*.zst
# [ -d video ] && mv video/*.h265 . && rm -rf video/
# rm -f "*upload*"
